# Generated by Django 4.0.3 on 2022-03-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField()),
                ('incorrect_answers', models.IntegerField()),
            ],
        ),
    ]
